### ISSUE TITLE
Change last vapor references to complete rebrand to Plasma

### ISSUE THREAD

**Issue by MichelML** [coveo/plasma#2368]
Nice rebrand!

Some missing changes here:

![image](https://user-images.githubusercontent.com/9539763/146973631-77a0a7b9-db0f-4663-97ef-0b91fb346776.png)

![image](https://user-images.githubusercontent.com/9539763/146973669-1d9b10b7-b07d-4375-81e3-e905ad7ea0ff.png)

**Comment by MichelML** [comment]
sorry just saw https://github.com/coveo/plasma/pull/2367

feel free to close anytime :100:

**Comment by GermainBergeron** [comment]
Thanks Michel!

We actually have a few other things to change in our infra for the url but I'll keep that in mind 😄
